[tool.poetry]
name = "traefik-to-unifi"
version = "0.1.0"
description = ""
authors = ["Thomas Lomas <tlomas@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
schedule = "^1.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
